import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import Products from "@/components/Products";
import { GetServerSideProps } from "next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

type Props = {
  initialItems: any[];
}

export default function Home({ initialItems }: Props) {
  return (
    <>
      <Head>
        <title>Product Web</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <h1 className={styles.title}>Our Products</h1>
          <Products />
        </main>
      </div>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const query = context.query.q || ''; // Get the query string (if any)
  const response = await fetch(`https://my-json-server.typicode.com/luthfihadiana/product-web/posts?q=${query}`);
  const initialItems = await response.json();

  return {
    props: {
      initialItems,
    },
  };
};
