import { getProductDetail } from "@/services";
import { ProductItem } from "@/types";
import { GetServerSideProps } from "next";
import Head from "next/head";
import Page from "@/components/Page";
import styles from "@/styles/Details.module.scss";
import Category from "@/components/Category";
import { useRouter } from "next/router";

type Props = {
  item: ProductItem;
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const query = context.query.id || 0; // Get the query string (if any)
  try {
    const item = await getProductDetail({ id: Number(query) });

    return {
      props: {
        item,
      },
    };
  } catch {
    return {
      props: {
        item: {
          name: "",
          categories: [],
          id: 0,
          image_url: "",
          price: 0
        },
      },
    };
  }
};

export default function Home({ item }: Props) {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Product Web - {item.name}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page>
        <div className={styles.productHeader}>
          <span className={`material-symbols-outlined ${styles.productHeaderBack}`} onClick={() => router.push("/")}>
            arrow_back
          </span>
          <h1 className={styles.title}>
            {item.name}
          </h1>

        </div>
        <img className={styles.productImage} src={item.image_url} />
        <div className={styles.productCategories}>
          {
            item?.categories.map(el => (
              <Category category={el} key={`${item.id}-${el}`} />
            ))
          }
        </div>
        <div className={styles.productDescription}>
          <p>
            {item?.description}
          </p>
        </div>
        <div className={styles.productInfoContainer}>
          <div className={styles.productInfo}>
            <p>
              <span className="material-symbols-outlined">
                thumb_up
              </span>
              {item.likes ?? 0}
            </p>
            <p>
              <span className="material-symbols-outlined">
                shopping_cart
              </span>
              {item.sold_number ?? 0}
            </p>
            <p>${item.price}</p>
          </div>
        </div>
      </Page>
    </>
  );
}
